### ISSUE TITLE
Snippet Length (5 hr)

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#10]
- Reduce snippets to acceptable length as per Cambridge copyright requirements

**Comment by smurp** [comment]
Could someone interpret those requirements into directions I might follow?

**Comment by ilovan** [comment]
I believe this is caused by the fact that Orlando materials are copyrighted by Cambridge University Press and that exposing large chunks of Orlando text in the snippets to users/testers that don't have an Orlando subscription might constitute copyright infringement (I can't tell you what's the maximum length allowed, but I am sure @SusanBrown knows.)

Just checking: is the content and length of the snippet determined by xPath only or could we possibly truncate further?

**Comment by smurp** [comment]
When generating the snippets we are only working from the structural id of the site which triggered the creation of the triple.  On the server side the tag with that id is found and the text contained within the tag returned as the snippet.

In other words we can truncate however we want.  

Note that there are some triples triggered by XML tags which are, in fact, empty and consequently have no snippet length at all.  Sorry, I can't remember any examples.

**Comment by jsmithelford** [comment]
We need to link to the Cambridge Database as well.

**Comment by cmiya** [comment]
- Limit to "200" characters
- Start at the beginning of a paragraph and end at a period.
-if we can't start at the beginning of a paragraph, go to nearest period before the search term.
-Include a link to the Cambridge author entry, and target specific spot if possible.

**Comment by smurp** [comment]
@jsmithelford  If I recall correctly the author name acts as a link to the
Cambridge page for the author.  If something else is desired could it be
described?

On Thu, Oct 1, 2015 at 8:56 AM, cmiya <notifications@github.com> wrote:

>
>    - Limit to "200" characters
>    - Start at the beginning of a paragraph and end at a period. -if we
>    can't start at the beginning of a paragraph, go to nearest period before
>    the search term. -Include a link to the Cambridge author entry, and target
>    specific spot if possible.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cwrc/HuViz/issues/10#issuecomment-144770882>.
>



-- 
Shawn Murphy
smurp@smurp.com
(780) 903-2428
http://www.smurp.com

**Comment by smurp** [comment]
@cmiya Could someone familiar with the Cambridge site tell me what the url
format for those "target specific spots" might look like?  Failing that
could someone in the know establish an account for me as "
smurpster@gmail.com" as it appears I failed to save my password for my
(probably "smurp@smurp.com") account for that site.

On Thu, Oct 1, 2015 at 1:38 PM, Shawn Murphy <smurp@smurp.com> wrote:

> @jsmithelford  If I recall correctly the author name acts as a link to the
> Cambridge page for the author.  If something else is desired could it be
> described?
>
> On Thu, Oct 1, 2015 at 8:56 AM, cmiya <notifications@github.com> wrote:
>
>>
>>    - Limit to "200" characters
>>    - Start at the beginning of a paragraph and end at a period. -if we
>>    can't start at the beginning of a paragraph, go to nearest period before
>>    the search term. -Include a link to the Cambridge author entry, and target
>>    specific spot if possible.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cwrc/HuViz/issues/10#issuecomment-144770882>.
>>
>
>
>
> --
> Shawn Murphy
> smurp@smurp.com
> (780) 903-2428
> http://www.smurp.com
>



-- 
Shawn Murphy
smurp@smurp.com
(780) 903-2428
http://www.smurp.com

**Comment by smurp** [comment]
@cmiya The inclusion of text from outside the target tag "nearest period before the search term" and the "target specific spot" change this from 1hrs to 5hrs.

**Comment by SusanBrown** [comment]
Can you suggest a more efficient way of arriving at a readable snippet than this one?

As far as the targets go, I think we need to consult with @jsympson@gmail.com or @jeffery.antoniuk@ualberta.ca (just guessing at email addresses while answering from email, so this may need to be forwarded to them). I understood in our meeting that the mode of pointing to targets had been established. If not, then we may need for the moment just to link to the whole entry.

**Comment by ilovan** [comment]
My understanding was that once we switch from RegEx to Xpath it would be easier to target specific tags. 

@smurp , if you happen to have a valid UofA ccid, then you have access to the Orlando site through UofA libraries (http://www.library.ualberta.ca/databases/browse_by_letter/index.cfm?fuseaction=firstletter&letter=o). 
If not, let me know and I'll discuss with @jefferya and @SusanBrown about possible ways to get you access.

**Comment by smurp** [comment]
I don't have a CCID.  I'm so sorry, I recall having had access to the
Cambridge site -- provided by Jeffery I believe -- but failed it add the
credentials to my encrypted account database, apparently thinking them
'unforgettable'.  They certainly do seem to be unretrievable anyway.  Sigh
and sigh.

On Tue, Oct 13, 2015 at 2:23 PM, Mihaela Ilovan <notifications@github.com>
wrote:

> My understanding was that once we switch from RegEx to Xpath it would be
> easier to target specific tags.
>
> @smurp <https://github.com/smurp> , if you happen to have a valid UofA
> ccid, then you have access to the Orlando site through UofA libraries (
> http://www.library.ualberta.ca/databases/browse_by_letter/index.cfm?fuseaction=firstletter&letter=o).
>
> If not, let me know and I'll discuss with @jefferya
> <https://github.com/jefferya> and @SusanBrown
> <https://github.com/SusanBrown> about possible ways to get you access.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cwrc/HuViz/issues/10#issuecomment-147841287>.
>



-- 
Shawn Murphy
smurp@smurp.com
(780) 903-2428
http://www.smurp.com

**Comment by jefferya** [comment]
I'm likely missing context since I'm entering the conversation in the
middle so please bare with me as I try to catch-up.

First, what is trying to be accomplished by accessing the Cambridge Orlando
site? The reason I ask is that we don't have the ability to give out access
credentials to the Cambridge site - we can request a UofA CCID (but I don't
know if it comes with Cambridge Orlando access). That being said, there
might be other ways to accomplish the goal but I'm in the dark as to the
end goal. Can you fill me in?

Reading the words "target specific tag", "snippet", and "Cambridge" in the
same discussion set off warning bells in my head. Part of the reason, the
Cambridge site was never designed to interoperate with any external tools.

**Comment by SusanBrown** [comment]
I think I can shine a bit of light here.

1) For the purpose of actually rendering the snippets, Shawn/HuViz needs access to the current CUP content but not necessarily to the CUP site itself. 

2) However, the links that HuViz provides for getting back to the source of snippets (ideally something more granular than the front screen of the entry itself but the internal screen/section of screen) DO need to refer to the CUP site.

Jeff, if you can easily reissue a pw to Shawn for the CUP site, that might be helpful, but I think the main challenge here is how we link more precisely to snippets within Orlando, and giving him access to that site is not going to solve that problem. It probably require a meeting between Jeff, Shawn, John and me.


On October 26, 2015 at 6:28:59 PM, Jeffery Antoniuk (notifications@github.com) wrote:

I'm likely missing context since I'm entering the conversation in the
middle so please bare with me as I try to catch-up.

First, what is trying to be accomplished by accessing the Cambridge Orlando
site? The reason I ask is that we don't have the ability to give out access
credentials to the Cambridge site - we can request a UofA CCID (but I don't
know if it comes with Cambridge Orlando access). That being said, there
might be other ways to accomplish the goal but I'm in the dark as to the
end goal. Can you fill me in?

Reading the words "target specific tag", "snippet", and "Cambridge" in the
same discussion set off warning bells in my head. Part of the reason, the
Cambridge site was never designed to interoperate with any external tools.

**Comment by SusanBrown** [comment]
I had a chat with Jeff about this today. It's going to take some work on the Orlando side to get targeted snipped links working, and we need to think it through in terms of versioning.
For now, continue to link to the overview page of the author's Orlando entry at CUP.

So I think that this issue boils down to:
--    Limit to "200" characters
--    Start at the beginning of a paragraph and end at a period if possible (preference for starting at beginning of nearest paragraph to the search term). 
--   If we can't start at the beginning of a paragraph, go to nearest period before the search term. 
--  Include a link to the Cambridge author entry's Overview screen. 
--  Format for the URL for Celia Fiennes: http://orlando.cambridge.org/public/svPeople?person_id=fience
All the links to the published authors entries are available here: http://www.artsrn.ualberta.ca/orlando/?page_id=81 but I think they were already being successfully incorporated into the the RDF, since links were working.

**Comment by cmiya** [comment]
@smurp could we make this a **priority task** for the next milestone deadline (Jan. 31) because we are currently violating Cambridge UP's copyright laws. The div1 windows seem to be fine (correct length, etc), but the div0's with the full text are still popping up.

**Comment by smurp** [comment]
The ambition here is to restore my access to the Cambridge site so I can
scope out whatever possibilities might exist for deep linking into the
corpus presented there.  In particular, when one is reading a snippet it
would be desirable to see the snippet in context and hence desirable to be
able to click on a "deep link" back to the Cambridge site which took the
user as close as possible to the snippet.  We've got the context of the
structural tags (and possibly other related ids if need be) so the
questions are things like:
1) are there html <A NAME=...> tags or elements with ID attributes in the
Cambridge viewer which would be suitable targets
2) which things there have such targets
3) what are those target identifiers and do they have a trivial
relationship to the ids in our XML or are we going to have to implement
some sophisticated processing.

Rather than burden anybody else with trying to figure this stuff out and
communicate it to me, it seems easiest if I could just do it myself.
Again, apologies for having forgotten my credentials, presumably a CCID?!?

On Mon, Oct 26, 2015 at 4:28 PM, Jeffery Antoniuk <notifications@github.com>
wrote:

> I'm likely missing context since I'm entering the conversation in the
> middle so please bare with me as I try to catch-up.
>
> First, what is trying to be accomplished by accessing the Cambridge Orlando
> site? The reason I ask is that we don't have the ability to give out access
> credentials to the Cambridge site - we can request a UofA CCID (but I don't
> know if it comes with Cambridge Orlando access). That being said, there
> might be other ways to accomplish the goal but I'm in the dark as to the
> end goal. Can you fill me in?
>
> Reading the words "target specific tag", "snippet", and "Cambridge" in the
> same discussion set off warning bells in my head. Part of the reason, the
> Cambridge site was never designed to interoperate with any external tools.
>
>
>
> On Mon, Oct 26, 2015 at 2:26 PM, Shawn Murphy <notifications@github.com>
> wrote:
>
> > I don't have a CCID. I'm so sorry, I recall having had access to the
> > Cambridge site -- provided by Jeffery I believe -- but failed it add the
> > credentials to my encrypted account database, apparently thinking them
> > 'unforgettable'. They certainly do seem to be unretrievable anyway. Sigh
> > and sigh.
> >
> > On Tue, Oct 13, 2015 at 2:23 PM, Mihaela Ilovan <
> notifications@github.com>
> > wrote:
> >
> > > My understanding was that once we switch from RegEx to Xpath it would
> be
> > > easier to target specific tags.
> > >
> > > @smurp <https://github.com/smurp> , if you happen to have a valid UofA
> > > ccid, then you have access to the Orlando site through UofA libraries (
> > >
> >
> http://www.library.ualberta.ca/databases/browse_by_letter/index.cfm?fuseaction=firstletter&letter=o
> > ).
> > >
> > > If not, let me know and I'll discuss with @jefferya
> > > <https://github.com/jefferya> and @SusanBrown
> > > <https://github.com/SusanBrown> about possible ways to get you access.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/cwrc/HuViz/issues/10#issuecomment-147841287>.
> > >
> >
> >
> >
> > --
> > Shawn Murphy
> > smurp@smurp.com
> > (780) 903-2428
> > http://www.smurp.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cwrc/HuViz/issues/10#issuecomment-151274280>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cwrc/HuViz/issues/10#issuecomment-151302950>.
>



-- 
Shawn Murphy
smurp@smurp.com
(780) 903-2428
http://www.smurp.com

**Comment by smurp** [comment]
Will do, Chelsea.

On Mon, Jan 18, 2016 at 5:35 PM, cmiya <notifications@github.com> wrote:

> @smurp <https://github.com/smurp> could we make this a *priority task*
> for the next milestone deadline (Jan. 31) because we are currently
> violating Cambridge UP's copyright laws. The div1 windows seem to be fine
> (correct length, etc), but the div0's with the full text are still popping
> up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cwrc/HuViz/issues/10#issuecomment-172692452>.
>



-- 
Shawn Murphy
smurp@smurp.com
(780) 903-2428
http://www.smurp.com

**Comment by jefferya** [comment]
Hi Shawn,

The CUP site was never designed for deep linking, just surface linking to
the main object (e.g. free-standing event, bio doc, writing doc,
bibliographic item.

Note, the IDs in the XML change nightly. They are not persistent. The IDs
were only ever meant to be used in the context of the CUP site  (i.e.,
internally not externally because they have no persistence and can change
nightly). Because of this, I don't believe #1, #2, or #3 are feasible
(i.e., each may work for a period of time or on many instances but
 spurious errors are going to appear due to the lack of persistence.) Can I
make these IDs persist? No, these are automatically generated within the
context of the CUP (i.e., delivery site) and do not live in the original
documents edited by the users.This is a case where appearances are
deceiving. The only way the IDs could potentially be used is if HuViz and
the CUP site were using the same backend (i.e. integrated together or
people were very careful to make sure both were using exactly and I mean
exactly the same version of the textbase) otherwise spurious errors will be
introduced due to the lack of ID persistence. The only IDs that persist are
the object level IDs (i.e. event id, bio doc id, writing doc id,
bibliographic id - no ids for snippets or core tags within the xhtml
output).

The Nov 26/27 conversation in this thread still applies.

Shawn, do you have access to the UofA VPN or library proxy? This credential
will work.

Cheers,
~Jeff

**Comment by smurp** [comment]
The work to shorten snippets by eliminating `DIV0--1` from was in 58c5511 e8e6a1e and e64e5be.

I believe that this work satisfies the goal of suppressing full article dumps

**Comment by SusanBrown** [comment]
Should do. Thanks. Had a meeting with CUP the week before last and they were quite enthusiastic about HuViz as an alternative route into Orlando, so as long as we’re not publishing full articles, I think we’re good on that score.

**Comment by smurp** [comment]
Wonderful!

On Tue, Mar 22, 2016 at 12:26 PM, SusanBrown <notifications@github.com>
wrote:

> Should do. Thanks. Had a meeting with CUP the week before last and they
> were quite enthusiastic about HuViz as an alternative route into Orlando,
> so as long as we’re not publishing full articles, I think we’re good on
> that score.
>
> > On Mar 22, 2016, at 2:17 PM, Shawn Murphy <notifications@github.com>
> wrote:
> >
> > The work to shorten snippets by eliminating DIV0--1 from was in 58c5511 <
> https://github.com/cwrc/HuViz/commit/58c551165771d9b83818e4fbf747c4724fc88f3b>
> e8e6a1e <
> https://github.com/cwrc/HuViz/commit/e8e6a1e4ff2958b9f179a5a12b5136dd01b9795f>
> and e64e5be <
> https://github.com/cwrc/HuViz/commit/e64e5bee29d300ca31f6b50038ffb176b6b658cd
> >.
> >
> > I believe that this work satisfies the goal of suppressing full article
> dumps
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub <
> https://github.com/cwrc/HuViz/issues/10#issuecomment-199948055>
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/cwrc/HuViz/issues/10#issuecomment-199951350>
>



-- 
Shawn Murphy
smurp@smurp.com
(780) 903-2428
http://www.smurp.com
