### ISSUE TITLE
Truncate Node Labels (1.5 hr)

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#14]
- Labels need to be truncated. In other words, links that have long connection names because of the nature of rdf need to be cut down to a specific character length. Ie: see abdyma

**Comment by smurp** [comment]
This should in large measure be addressed by the move to xpath-based conversion to RDF from the older regex technique --- AND there should be some capping of label length (or maybe implement marquee-style scrolling on hover?)

**Comment by cmiya** [comment]
Great! Thanks for clearing that up.

**Comment by smurp** [comment]
Proposal:
* [ ] cap the display of label contents at 40 characters
* [ ] implement marquee-style scrolling of the contents of the label for the `target node` (the node currently being hovered over) http://goo.gl/LVoMWB

**Comment by ilovan** [comment]
I like the idea of marquee-style scrolling

**Comment by smurp** [comment]
closed with https://github.com/smurp/huviz/commit/0e6d65d

OK the scrolling and truncating now work very nicely and have a slider over on the Settings tab called "truncate and scroll".  A good way to see this in action is to do:
  Label All.

Then adjust the "truncate and scroll" slider to taste.  It defaults to 40.

Note that the scrolling happens on every update so looks a little fast, but I've left it like that for the moment because it offers an interesting affordance: halting mouse movement over a scrolling label halts the scrolling and then slow mouse motion lets you manually control the scroll with a gentle sawing action.  Unusual, but it emerged and rather than rush ahead and implement a timer to rate-limit the scrolling I thought I'd leave it like this for the moment for feedback.

It's deployed on both alpha and beta sites.
