### ISSUE TITLE
Problems Selecting Verbs (0 hrs)

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#16]
Very difficult to tell which verbs I have selected. Sometimes a box will go dark after I have clicked it, sometimes not. Sometimes a dark box will randomly change to light or vice versa when I move away my cursor (without having clicked anything else). Also, the text inside the hover bubble does not always match the verbs I have selected (according to the text that appears in the yellow command line). So the three ways of knowing which verb is selected (text box colour, hover bubble, yellow command line text) often appear to contradict each other.

NOTES:
- It would really help if the cursor was a pointer not a text bar because a bar indicates to the user that area is for typing, not clicking.
- It would also be helpful if the boxes changed when the user hovered over them (EX: with a halo around the box), so that the user would know if they were clickable.

**Comment by smurp** [comment]
When only a single verb has been activated in the verb picker then whenever one hovers over nodes in the graph the activated verb automatically updates to reflect the state of the "target node", ie the node which will be affected with a click.  Consider the `label` verb.  If it is the only verb activated then hovering over an unlabeled node will leave the `label` verb activated so that clicking will cause that node's label to appear permanently.  Once the click has happened and the cursor is still hovering over the node then the activated verb becomes `unlabel` because that is the thing that a person would want to be able to do to the node in its current state.  

The verbs are organized in `VERB`/``unVERB` pairs: `label/unlabel`, `select/unselect`, `choose/unchoose`, etc and these are the pairs between which these automatic togglings occur.

There is certainly work to be done to complete the updating of the current command box, as this automatic toggling behaviour is still new and not fully realized with respect to the command box.  Let's figure out the right visual cues!

**Comment by cmiya** [comment]
In the case of the automatic toggling (when a node will always either be in one state or another) would it simplify the display if we showed just ONE button (ex: label) that was either highlighted (to indicate active) OR unhighlighted (to indicate not active)? From my perspective, this would declutter the toolbar and simplify things for the user.

**Comment by cmiya** [comment]
As mentioned, could be addressed by #36
