### ISSUE TITLE
Ontology not loading with new data file

### ISSUE THREAD

**Issue by antimony27** [cwrc/HuViz#165]
I've created a new data file here: https://github.com/cwrc/testData/blob/master/demoData/CulturalFormationTriplesforExtraction.ttl

When I try to load it into alpha, it just creates a graph without letting me load the ontology. I've tried loading it directly from my computer, and via a link from GitHub, and neither attempt is making a difference. 

@smurp Any thoughts on why this might be happening?

**Comment by SusanBrown** [comment]
Just to avoid confusion, could you please provide the full address you’re using for alpha, Kim? And did you also try it on beta?

On Jul 18, 2018, at 5:44 PM, antimony27 <notifications@github.com<mailto:notifications@github.com>> wrote:


I've created a new data file here: https://github.com/cwrc/testData/blob/master/demoData/CulturalFormationTriplesforExtraction.ttl

When I try to load it into alpha, it just creates a graph without letting me load the ontology. I've tried loading it directly from my computer, and via a link from GitHub, and neither attempt is making a difference.

@smurp<https://github.com/smurp> Any thoughts on why this might be happening?

**Comment by antimony27** [comment]
Just checked on this again. Still happening, but maybe just a problem with alpha. 

When I copy/paste the url (https://github.com/cwrc/testData/blob/master/demoData/CulturalFormationTriplesforExtraction.ttl) to alpha (http://alpha.huviz.dev.nooron.com/) and then select the CWRC ontology, the Go button wasn't going live and there was no way for me to click on it.

![image](https://user-images.githubusercontent.com/11494469/44527223-3814a000-a6b4-11e8-9cc0-77262a6b850b.png)

However - I've just realized that we now have to hit 'enter' after pasting in the URL (when we were dragging and dropping them in it did this automatically), so that solves that issue. @cmiya we'll have to make sure this is in the user tests/documentation.

**Comment by wolfmaul** [comment]
@antimony27 
Loading from this link:  https://github.com/cwrc/testData/blob/master/demoData/CulturalFormationTriplesforExtraction.ttl
will not work since this is not a proper ttl file (although it does look like it from the URL). The actual link to the file itself is through the Raw button.

<img width="964" alt="screen shot 2018-08-31 at 11 03 25 am" src="https://user-images.githubusercontent.com/11096332/44903962-34b19200-ad0e-11e8-801d-a59c1c3ff4d2.png">

Try this URL to the ttl file:
https://raw.githubusercontent.com/cwrc/testData/master/demoData/CulturalFormationTriplesforExtraction.ttl

**Comment by antimony27** [comment]
This dataset no longer relevant, and issue appeared to be an error on my part. Closing.
