### ISSUE TITLE
Hide VS Discard VS Shelve (0 hrs)

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#20]
PROBLEM:
-   Much like choose and select, it is difficult to distinguish between the verbs shelve, discard and hide.

SOLUTION:
-   Rename one or more of the verbs. I believe Susan had suggested changing the name of “hide” to “park.”
-   OR should we keep verbs as is and clarify the meaning through additional documentation?

---

CURRENT DEFINITIONS:

*

SHELVE: returns node to the shelf aka the node circle.
- Shelved nodes can be called into the graph automatically (either through the predicate picker or because they are hub nodes).

*

DISCARD: sends nodes to the discard bin, which appears as a red dot at the bottom right of the screen.
- Discarded nodes cannot be called back into the graph unless they are retrieved.
- Discarded nodes can be retrieved two ways:
  - 1) Dragging the node from the discard bin back to the circle.
  - 2) Selecting retrieve in the verb bar and clicking the node.
  - *Note: As always, you can use the all function to apply an action/verb to all nodes at the same time. In this case, selecting retrieve in the Verb bar and clicking all in the Sets bar (or vice versa) will retrieve all nodes at once. This is faster than dragging or clicking them individually.

*

HIDE: temporarily removes nodes from the dataset.
- They are completely hidden and no longer appear in the shelf or the discard bin. Their data is also removed from the Classes bar and the Edges of the Selected Nodes bar (For example, if you applied the verb hide to “fur trader,” the edges count in the connectedwithJob category of the Edges of the Selected Nodes bar would decreased by 1).
- BUT hidden nodes, while temporarily removed, are not permanently deleted from the dataset. Hidden nodes can be retrieved in two ways:
  - 1) Selecting all from the Sets bar and then clicking retrieve in the Verbs bar.
  - 2) Clicking the reset button.

**Comment by cmiya** [comment]
Again, if you have a different understanding of the terms and/or how they function, please post!

**Comment by ilovan** [comment]
your description matches my understanding

**Comment by smurp** [comment]
Right, hidden nodes just aren't visible but they can still be "drawn back into the graph" as a result of a node they are connected to having the "graph" verb applied to it -- eg by that node being dragged into the graph.

The constraints on naming are interesting because they should make sense in the context of their obverse verb.  Note that `shelve` and `hide` are not a verb-pair like `pin/unpin`, `label/unlabel` etc.

The challenge here is to come up with 6 words which all work together agreeably.  There is an upper limit on how agreeably that might be!  Documentation and pop-up training materials are the key, I think.

**Comment by cmiya** [comment]
I still think the semantic distinctions between the words Hide, Discard, Shelve (AND I would add "UnGraph) might be too subtle for users to intuitively grasp the function of these verbs. We don't want them to have to be continually referring back to the documentation.

**Comment by jsmithelford** [comment]
I would tend to this this is true (the distinctions between these words are too hard for a new user to grasp). However, if we do a good job of the hover/help/documentation funtionality, is it possible to move towards testing without making new terms?

**Comment by smurp** [comment]
# Proposal #

We could facilitate A/B testing of different sets of terms by adding an entry to the `Setting` tab which is a select box offering various canned sets of verb names.  These could be maintained in an external data structure (a .json file for example) which could be easily added to by non-developers.

This work would require abstracting all of the verb names so that their presentation to users would always be in the configured vocabulary.

## Steps ##
* [ ] abstract all verb names internally, so their presentation to users can be configured
* [ ] add a configuration entry **Verb Name Set** (or similar) which offered access to sets defined in an external .json file

**Comment by ilovan** [comment]
related to #39
