### ISSUE TITLE
geonames performing strangely

### ISSUE THREAD

**Issue by antimony27** [cwrc/HuViz#246]
A number of times tonight strange things have happened when I put 'huviz' into the geonames username option.  The main problem, from what I can tell, is that HuViz is pulling too much data from Geonames, even though I have not checked either 
![image](https://user-images.githubusercontent.com/11494469/51165121-0b744700-1854-11e9-84a0-4151a8eaf7ef.png)

## Steps to Reproduce
In Alpha, I loaded 
![image](https://user-images.githubusercontent.com/11494469/51165152-20e97100-1854-11e9-8aab-d8e1e11ec307.png)

I searched for 'pol' in the biography dataset, clicked on Horace Walpole and brought up his data in HuViz. There appears to be about 9 geonames nodes in the graph. I went to settings, typed 'huviz' in the geonames box, hit enter. Then I drag two nodes into the graph and all of a sudden there are at least 100 geonames nodes in the graph now:

![image](https://user-images.githubusercontent.com/11494469/51165383-dfa59100-1854-11e9-9016-89c2e1e89f55.png)

## Possible Solution
Might this have something to with the Sparql end point? It doesn't seem to happen with the datasets from the drop down menu. 

* [x] fix surprising extra nodes
* [ ] updating the Class counts for Thing and Place

**Comment by smurp** [comment]
I used the Endpoint and the Graph you suggested then searched for "Horace" and got him directly.  Then I ran these commands:

    Activate sws_geonames_org_7301442 .
    Activate sws_geonames_org_2643743 .

At this point there were 628 nodes in the All set and that was without messing with the Geonames Username

@antimony27 As far as I can tell this is the splendor of big data which we are experiencing here!  And also the excitement of recursion!  

Any thoughts on this one @wolf ?  

Until we get scripts easily shareable it is going to be pretty hard to reproduce such experiences, especially with SPARQL.

I'll perform some experiments to see if there is anything going on with Geonames Username which is exciting....

**Comment by antimony27** [comment]
Hmm... just followed all of your steps here Shawn - weird indeed. I'm adding Geonames to the meeting agenda for tomorrow, as there are quite a few things to chat about here.

**Comment by smurp** [comment]
Report on an extension to the experiment from Jan 16th reported above.

http://alpha.huviz.dev.nooron.com/#load+https://raw.githubusercontent.com/cwrc/testData/master/sparqlOutputs/jewish_novelist_biographies.ttl+with+http://sparql.cwrc.ca/ontology/cwrc.ttl

From here I did the following:
1. Clicked the Settings tab and put `huviz` into _Geonames Username_ and pressed `Enter`
2. Ran the command `Label and Activate Place .`
3. Ran the command `Unlabel and Discard the Graphed set .`
4. Noticed that the number in the Labelled Set is now 16.

These 16 nodes are disconnected from all other nodes, otherwise they would have been in the graph along with the rest of the Place nodes.  Notice that 16 is the number of the "surprising increase" discovered on Jan 16th.

These appear to be nodes introduced into the dataset by interaction with Geonames, but which weirdly are not connected to any other nodes.  

_To be continued....._

**Comment by smurp** [comment]
Replicating the Jan 16th experiment

### Before doing anything
![image](https://user-images.githubusercontent.com/774119/55388847-538e3600-5534-11e9-890c-96136f2f5b6f.png)

### After setting the `Geonames Username` to `huviz`

![image](https://user-images.githubusercontent.com/774119/55389014-b384dc80-5534-11e9-888a-d022570e572e.png)

### Changes

| Set | Before | After | Δ |
|---|---|---|---|
| All | 254 | 270 | +16 |
| Nameless | 168 | 147 | -21 |
| Shelved | 253 | 263 | +10 |

**Comment by smurp** [comment]
The surprising extra nodes are fixed by https://github.com/smurp/huviz/commit/4b661c22f1a534ee2bbb626bdd091143b1d49f75

There remains the issue that the counts on the new Place class and the Thing class do not immediately adjust after geonames completion

**Comment by smurp** [comment]
There also remains the issue that the geoname limit setting is effectively ignored thanks to a race condition.

**Comment by smurp** [comment]
With https://github.com/smurp/huviz/commit/629c7f483bf82bc3a08ff9805bd4f41e266673ec the code now welcomes geonames which are with or without:

* https
* www
* trailing slashes

**Comment by antimony27** [comment]
Again - does not reflect current state of things. Closing.
