### ISSUE TITLE
After Activate verb shifts to deactivate

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/HuViz#250]
If you Activate All , the verb changes to Deactivate without user intervention and even if the user selects another verb it gets added to Deactivate rather than replacing it.

**Comment by antimony27** [comment]
Playing around to see what happens with this. In Alpha using WoolfsOrlando, this happens briefly. For example:
1. I click on activate
2. I click on DH Lawrence **If you watch the Command Panel, it flickers between Activate and Deactivate**
3. I click on Orlando-Work **It does this again**

I think this might be because you are still technically engaging the original node, and you can't re-activate it, so it defaults to DeActivate. But this shouldn't be the case when you hover over other nodes. 

@smurp ?

**Comment by antimony27** [comment]
Seems to be rectified.
