### ISSUE TITLE
Debug and Document the History (SCRIPT) Tab (1 hr)

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#26]
- What is the purpose of the History Tab? It doesn’t seem to record all of the actions (like shelving) that are performed (possible BUG?)
- Might be helpful if it listed node labels that actions were applied to (as opposed to just general actions). - If History Tab is meant to keep a record of actions (in order to duplicate results), might be better achieved by a "Save" function.

**Comment by ilovan** [comment]
mostly covered by #8.

**Comment by smurp** [comment]
@cmiya The history tab not showing the selection operations is because selected-ness by itself does not actually alter the state of the graph, just the state of the class and predicate pickers.  Think of "select" like  a selection in a word-processing document -- the selected things are what you are working with at the moment and are the set of things which will be affected by the next command completion.

That's not to say I'm right in thinking that selection activities shouldn't appear in the history tab, that is just what motivated them not having that effect.

When the Save function comes, it will be built on the data accumulated in the history tab.  Whether users see the history is of course optional.  What I had been thinking though was that a visible history does these things:
* provide a way for users to see what they have done in a readable way, reinforcing the "linguistic interface" aspect of the system where the history is revealing the clicky-draggy activities of the user as actually being the execution of imperative commands of the form `verb-phrase object-phrase`.
* provide access to the history so users can easily go back to an earlier state of the graph
* make each point in the history be able to produce a link which saves or contains a script consisting of the commands to that point (but now we're talking about saving and how to do that, which needs its own discussion, apparently over in #8 )

**Comment by jsmithelford** [comment]
I'm not sure this needs to be addressed before user testing, if the Save function will come later.

**Comment by cmiya** [comment]
True, although we might want to think through what a "Save" function would look like, so we can get feedback from users on whether they would find it useful and what specifically they might use it for.

**Comment by jsmithelford** [comment]
History tab broken. Maybe rename to script? Or something else (later date). Instead: an explanation of what it will do.

**Comment by smurp** [comment]
Proposal: 
* [ ] we rename it **Script** and 
* [ ] get it working again, given that it is probably a one-line fix anyway.

**Comment by susanirenebrown** [comment]
Yes: Script is great!

**Comment by cmiya** [comment]
I think this sounds like a great plan. I also like the idea of renaming it "script."

**Comment by ilovan** [comment]
Decision: 
For user testing: relabel "Coming soon"( #45)

For after user testing:
This issue seems closely interlinked with #8 and #32 and we feel that they should be worked on together. @smurp , can we get a combined estimate?

**Comment by smurp** [comment]
Amusing that time spent fiddling with the issues about this could have been
spent performing the task.

On Thu, Oct 1, 2015 at 8:43 AM, Mihaela Ilovan <notifications@github.com>
wrote:

> Decision:
> For user testing: relabel "Coming soon"( #45
> <https://github.com/cwrc/HuViz/issues/45>)
>
> For after user testing:
> This issue seems closely interlinked with #8
> <https://github.com/cwrc/HuViz/issues/8> and #32
> <https://github.com/cwrc/HuViz/issues/32> and we feel that they should be
> worked on together. @smurp <https://github.com/smurp> , can we get a
> combined estimate?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cwrc/HuViz/issues/26#issuecomment-144766776>.
>



-- 
Shawn Murphy
smurp@smurp.com
(780) 903-2428
http://www.smurp.com

**Comment by smurp** [comment]
Hey @wolfmaul could you spruce up the formatting of the command `History` tab? It was restored in https://github.com/smurp/huviz/commit/3be39d129c9db381343939cba78235c584015cde
