### ISSUE TITLE
Fix the Bug that Limits Large Datasets (3 to 9 days)

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#35]
HuViz performs best when handling ego networks with a limited number of connections (like R. M. Ballantyne). But as the number of entities and connections increase, the slower it loads and the more likely it is to crash. This poses a significant problem, as the tool was created precisely with these larger, more complex networks in mind. Is this an issue that we can fix in programming? What is the upper-limit to the amount of data that a browser-based tool can handle? Will the server ever be powerful enough to host large datasets (like poetess) with thousands (or tens of thousands) of connections?

**Comment by cmiya** [comment]
Perhaps these are issues that have already been worked through. But I wanted to get a handle on the source of the crashes before compiling the criteria for the new test datasets.

**Comment by cmiya** [comment]
Related to #17, #29, #30, #31, #13, #12

**Comment by smurp** [comment]
I believe there is a bug causing excessive recursion which is likely the dominant performance issue during execution (after loading has happened) as well as being part of the cost of loading data.  Of course, being a bug, it ought to be fixable.

Caching of data in the user's browser between sessions and between datasets is under development in the Nooron context (where HuViz is also running).  See a dated example here:  http://libnoo.ponderate.com/  (click foaf20140414.nq for a medium sized dataset or schema.org.nt for a rather large one).  Data caching is not yet happening in this demo.  Again, under development.

I am also planning an url compression and url fragment datastructure for the cache and data transfer which ought to have an impact on data size and (likely) performance.

Graph rendering using webgl is back-burned but will make the display absolutely blister.

Between these various issues I am certain that very dramatic improvements in performance are coming. 

We are no where near the performance limits of a web-based graph visualization experience.

**Comment by cmiya** [comment]
Thanks for laying it out! This is really helpful. It's great to know that it's a fixable bug that is causing the crashes and that there are multiple ways to drastically improve speed/performance.

**Comment by smurp** [comment]
I suggest we budget an amount of time to pursuing this bug with the understanding that I can't promise to actually fix it in any particular period.  There is some pretty fancy stuff interacting in there: recursion, callbacks and messages that together make for a rather complex debugging situation.  I have actually already written some special tracing instrumentation (worthy of being released in its own right) to examine this issue, so both have a good starting point and a healthy respect for this issue.

**Comment by smurp** [comment]
There would unlikely be progress in under 6 hrs.

**Comment by cmiya** [comment]
In that case - is it something that we can wait to address until after user testing? Since we have other more pressing issues, I personally think that might be the best thing.

**Comment by SusanBrown** [comment]
I agree.

**Comment by smurp** [comment]
Agreed.  Important but doesn't really interfere with this testability pass.

**Comment by cmiya** [comment]
Sounds good to me. Unless there are any objections I'm going to clear the milestone.

**Comment by smurp** [comment]
## too long; don't read (here to communicate what is going on, for reference)

There are several things which might be contributing to these performance issues.

The (de)selection of each node (or class) causes a new recursive call which calculates the "english" version of what is selected. The remedy is likely to ensure that if a bulk operation is occurring (a class or a set is clicked) then the re-calculation of the "english" is delayed until all the nodes have been accounted for.

Likewise the (de)selection of each node (or class) causes a recursive call which calculates the state of colouring and numeric summarization of the "Edge Picker".  Bulk operations (a class or a set is clicked) should delay the recursive summarization until after all nodes have been accounted for.

The reason there are non-optimalities in these areas is because it is quite challenging to distinguish these operational contexts from one another given that there are so many ways that operations can be triggered and they all affect one another, ie affect the various pickers, command summaries and graph representations which are simultaneously displays and inputs:
* command execution
* verb engagement
* class engagement
* predicate engagement
* node dragging

Keeping all of the above working while fixing these excess recursion problems is going to require the creation of new tests.

Another challenge is that the environment is in principle already open to new nodes entering the dataset dynamically and causing many of the aforementioned updates when they do.  Something that is not yet supported is having interactions with nodes and pickers dynamically pull new data into HuViz from the server.  Since these requirements are immediately desired too, it is tempting to at least keep an eye on those needs while doing the above work.¯

**Comment by SusanBrown** [comment]
Just to double check, Shawn, you’re not proceeding with this now, right? We’re looking to clear the last of very few remaining issues prior to testing, but this isn’t one of them, I believe.

**Comment by cmiya** [comment]
@SusanBrown (*Shawn, correct me if I'm wrong) I think the reason to think-through and evaluate what these tasks might entail is in order to get estimates for the new contract. So, they are not being moved forward on, yet, just roughly planned out.

**Comment by susanirenebrown** [comment]
I realized that this was probably what was going on after I wrote that—sorry, my bad.

Chelsea, the ethics process will take up to 3 weeks. Where are we in terms of any outstanding issues related to testing?

**Comment by cmiya** [comment]
These are the [testing-related issues](https://github.com/cwrc/HuViz/milestones/Ready%20for%20User%20Testing) that still need to be complete. In terms of documentation tasks, I've closed #46. #3 is done. I would like to update the complete documentation again after the changes, but it actually has no impact on testing because the information/tasks are imbedded in the survey.

**Comment by cmiya** [comment]
If we have three weeks to wait for the ethics approval, @smurp could you have the [testing-related issues ](https://github.com/cwrc/HuViz/milestones/Ready%20for%20User%20Testing) finished by May 6th? That way we can move directly to testing once we get clearance. *Apologies for clogging up this thread, Shawn! But it would be good to get this sorted now.

**Comment by ilovan** [comment]
Hi @smurp ,
I concur with @cmiya . Is May 6th  areasonable deadline for the completion of the  testing-related issues?

**Comment by susanirenebrown** [comment]
Yes, if we’re lucky we’ll get clearance next week, and it would be good to be ready to go, finally!

**Comment by antimony27** [comment]
@smurp I think the recursion issue has been put to rest. If you agree, can you close this ticket?

**Comment by smurp** [comment]
If memory serves, these commits were key to squashing the recursion issues.

https://github.com/smurp/huviz/commit/33d040b6e5ca0f869e6ec85460ca5ced1d3630ef https://github.com/smurp/huviz/commit/9e4c0badf172692d4aba8aae5f1083d794a08d1f
