### ISSUE TITLE
change label for the class picker to "Class Selector"

### ISSUE THREAD

**Issue by smurp** [cwrc/HuViz#59]
This makes it more understandable what is happening in the class picker.

**Comment by smurp** [comment]
In keeping with this relabelling I also changed the blank Current Command prompt from `VERB SET/CLASS` to `VERB SET/SELECTION` because what the verb really operates on is the current selection.

**Comment by cmiya** [comment]
If possible - I would actually prefer to keep it as Verb Set/Class for now. Changing it at this point would mean going back into the DITA documentation and altering the instructions and recapturing the accompanying images, etc. Personally, I find the Set/Class categories helpful (because that is how the bins are labelled in the Commands Tab), but I get where you're coming from (as nodes can be individually selected by clicking, etc.)

**Comment by susanirenebrown** [comment]
Chelsea, I see what you’re saying about the documentation. This comes out of a conversation Shawn and I had after I presented HuViz in my class. I think this would be a big advance in usability. We also talked about having the two panels work such that if you were using one the other would grey or fade out, since they essentially trump one another. This too would, I think, help a lot. Is there any way we can do a minimal revision of the documentation by just revising the text to flag the change, and leaving the screenshots as they are? I know that wouldn’t be ideal, but at the same time I do think that the relationship amongst all the objects in the command tab is so hard to figure out that anything we can do to make it clearer would be an advance.

**Comment by cmiya** [comment]
No, that makes sense. It's not a huge deal to make the changes and redo the images. I might as well just do both at the same time - it's a bit of extra work, but if the images/text instructions don't match up it will be confusing. I'll get on that tomorrow.

**Comment by smurp** [comment]
I'm working on the greying-out functionality but family stuff has gotten in
the way.  On it again now....

On Sun, Mar 6, 2016 at 3:31 PM, Susan Brown <notifications@github.com>
wrote:

> Chelsea, I see what you’re saying about the documentation. This comes out
> of a conversation Shawn and I had after I presented HuViz in my class. I
> think this would be a big advance in usability. We also talked about having
> the two panels work such that if you were using one the other would grey or
> fade out, since they essentially trump one another. This too would, I
> think, help a lot. Is there any way we can do a minimal revision of the
> documentation by just revising the text to flag the change, and leaving the
> screenshots as they are? I know that wouldn’t be ideal, but at the same
> time I do think that the relationship amongst all the objects in the
> command tab is so hard to figure out that anything we can do to make it
> clearer would be an advance.
>
> > On Mar 6, 2016, at 5:24 PM, cmiya <notifications@github.com> wrote:
> >
> > If possible - I would actually prefer to keep it as Verb Set/Class for
> now. Changing it at this point would mean going back into the DITA
> documentation and altering the instructions and recapturing the
> accompanying images, etc. Personally, I find the Set/Class categories
> helpful (because that is how the bins are labelled in the Commands Tab),
> but I get where you're coming from (as nodes can be individually selected
> by clicking, etc.)
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/cwrc/HuViz/issues/59#issuecomment-193008221>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cwrc/HuViz/issues/59#issuecomment-193008750>.
>



-- 
Shawn Murphy
smurp@smurp.com
(780) 903-2428
http://www.smurp.com
